### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by Jarmahent** [0x4447/eslint-plugin-0x4447#1]
rename repo to 

`eslint-plugin-0x4447` or eslint to fit package.json name

**Comment by davidgatti** [comment]
@Jarmahent and who should do this? :)

**Comment by Jarmahent** [comment]
I don't have a option to go to the settings and change it sorry!

**Comment by davidgatti** [comment]
@Jarmahent in that case you have to assigned me to this issue. An Issue with nobody assigned is a lonely issue with no owner, thus nobody can work on it.
