### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by davidgatti** [0x4447/eslint-plugin-0x4447#4]
# mystery @

https://github.com/0x4447/eslint-plugin-0x4447/blob/58cca03a561a1b01b6fe606cd0daa48614724563/lib/index.js#L2

What is this @ fileoverview?

# On hold file?

I'm assuming this file `comment-blocks.js` is the one regarding the comments, and right now on hold right?

# How to install?

in the README you write to run this command to add the custom rule `npm install eslint-plugin-0x4447 --save-dev`, but it dose not work for obvious reasons, should this rule be released to NPM?

**Comment by Jarmahent** [comment]
@davidgatti Correct this would be the rule regarding the comment padding.

**Comment by davidgatti** [comment]
OK, in this case I will release it to NPM under the company account.
